# Generated by Django 3.1 on 2021-05-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=20),
        ),
    ]
